#!/usr/bin/perl -w
#
# NAME:
# NA
#
# PURPOSE:
# NA
#
# REQUIREMENTS:
# NA
#
# INPUT:
# NA
#
# OUTPUT:
# NA
#
# NOTES:
# NA
#
# BUGS:
# NA
#
# AUTHOR:
# NA
#
# MODIFIED:
# NA
#
# CVS_ID:
# $Id: dir2nc,v 1.1 2009-02-15 00:32:36 steingod Exp $
#
#

use strict;
use Getopt::Std;

use vars qw($opt_i $opt_o);

sub usage;

my($ifd,$ofd);
my(@files,$file,$newfile);
my $txt2cdl = "./txt2cdl";
my $template = "../etc/template_ctd.cdl";
my $format = "itp";
my $ncgen = "/usr/bin/ncgen -b";

usage if !getopts('i:o:');
usage if ((! $opt_i) || (!$opt_o));
$ifd = $opt_i;
$ofd = $opt_o;

opendir(DIR, $ifd) || die "can't open $ifd $!";
@files = readdir(DIR);
closedir(DIR);

foreach $file (@files) {
    next if ($file !~ /dat$/);
    $newfile = $file;
    $newfile =~ s/\.dat/\.cdl/;
    print "Converting $file to $newfile\n";
    system("$txt2cdl -i $ifd/$file -o $ofd/$newfile -m $template -f $format;$ncgen -b $ofd/$newfile;rm $ofd/$newfile");
}

exit;
