#!/usr/bin/perl -w
#
# NAME:
# itpdir2nc
#
# PURPOSE:
# To generate NetCDF files for a directory full of ASCII files. NetCDF
# files are located within the same directory and a gzipped tar file is
# generated.
#
# REQUIREMENTS:
# NA
#
# INPUT:
# NA
#
# OUTPUT:
# NA
#
# NOTES:
# Thsi was originally developed to handle ITP data from WHOI, and is
# yet not fully flexible and handling commandline configuration for other
# file formats.
#
# BUGS:
# When applied to ITP data, some profiles seem to generate incorrect
# NetCDF files. The reason for this is yet not known as they look OK as do
# the CDL files.
#
# AUTHOR:
# Øystein Godøy, METNO/FOU, 15.02.2009
#
# MODIFIED:
# Øystein Godøy, METNO/FOU, 06.10.2009: Updated for files containing
# oxygen as well...
# Øystein Godøy, METNO/FOU, 09.05.2012: Added ITPs measuring oxygen.
# Øystein Godøy, METNO/FOU, 2012-11-06: Added new ITPs measuring oxygen.
# Modified behaviour according to ncgen behaviour.
#
# CVS_ID:
# $Id: itpdir2nc,v 1.7 2013-06-20 12:24:47 steingod Exp $
#

use strict;
use Getopt::Std;
#use Archive::Tar;

use vars qw($opt_i $opt_o);

sub usage;

my($ifd,$ofd,$dirname,@tmp,$tgzfile,$ncfile);
my(@files,$file,$newfile,@files2tar,$status,$template); 
my $txt2cdl = "./txt2cdl";
my $template1 = "../etc/template_ctd.cdl";
my $template2 = "../etc/template_ctd_oxygen.cdl";
my $format = "itp";
my $ncgen = "/usr/bin/ncgen -b";
my $tarcmd = "/bin/tar";
my @witho2 =
("itp06","itp13","itp23","itp29","itp43","itp48","itp49","itp51","itp52","itp54","itp57","itp58","itp60","itp64","itp65","itp68","itp69","itp72");

usage if !getopts('i:o:');
usage if ((! $opt_i));
$ifd = $opt_i;
$ofd = $ifd;

$dirname = $ofd;
@tmp = split /\//,$dirname;
$dirname = $tmp[$#tmp];

if (grep /$dirname/,@witho2) {
    $template = $template2;
} else {
    $template = $template1;
}

$tgzfile = "$dirname"."_"."$dirname"."ctd.tgz";

opendir(DIR, $ifd) || die "can't open $ifd $!";
@files = readdir(DIR);
closedir(DIR);

foreach $file (sort(@files)) {
    $status = 0;
    next if ($file !~ /grd.+dat$/);
    $newfile = $dirname."_".$file;
    $newfile =~ s/\.dat/\.cdl/;
    $ncfile = $newfile;
    $ncfile =~ s/\.cdl/\.nc/;
    print "Converting $file to $ncfile\n";
    $status = system("$txt2cdl -i $ifd/$file -o $ofd/$newfile -m $template -f $format;");
    next if ($status);
    $status = system("$ncgen -b $ofd/$newfile -o $ofd/$ncfile;rm $ofd/$newfile");
    warn "Could not manage $newfile" if ($status);
    push @files2tar,"$ncfile";
}

system("cd $ofd;$tarcmd -cvzf $ofd/$tgzfile @files2tar");

exit;

sub usage {
    print "itpdir2nc -i <idir>\n";
    print "\tidir: input directory\n";
    exit;
}
